# Generated by Django 2.2.3 on 2019-08-09 07:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('report_no', models.IntegerField(primary_key=True, serialize=False)),
                ('police_office_name', models.CharField(max_length=150)),
                ('police_office_province', models.IntegerField(choices=[(0, 'province 1'), (1, 'province 2'), (2, 'province 3'), (3, 'Gandaki'), (4, 'province 5'), (5, 'KarnaSli'), (6, 'Sudurpashchim')])),
                ('police_office_district', models.CharField(max_length=100)),
                ('no_of_vehicle_involved', models.IntegerField()),
                ('no_of_driver_involved', models.IntegerField()),
                ('no_of_passanger_involved', models.IntegerField()),
                ('no_of_pedestrian_involved', models.IntegerField()),
                ('accident_seriousness', models.IntegerField(choices=[(0, 'death'), (1, 'serious injury'), (2, 'simple injury'), (3, 'loss only')])),
                ('accident_date_and_time', models.DateField(default=datetime.date.today)),
                ('day_of_week', models.IntegerField(choices=[(0, 'sunday'), (1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thursday'), (5, 'friday'), (6, 'saturday')], null=True)),
                ('vehicle_control', models.IntegerField(choices=[(0, 'yes '), (1, 'spot map only'), (2, 'zebra crossing'), (3, 'police involved'), (4, 'traffic symbol'), (5, 'stop signal'), (6, 'wait , look , go signal'), (7, 'others')])),
                ('collision_type', models.IntegerField(choices=[(0, 'face to face'), (1, 'face and back'), (2, '90 degree angle'), (3, 'sideways collision'), (4, 'upside down , unable to move'), (5, 'collide with anythings inside road '), (6, 'collide with anythings outside road '), (7, 'collide with parked vehicle'), (8, 'collide with pedestrian'), (9, 'collide with animals'), (10, 'others')])),
                ('weather_condition', models.IntegerField(choices=[(0, 'clean weather'), (1, 'rainy'), (2, 'foggy'), (3, 'smoke and dust')])),
                ('lighting_condition', models.IntegerField(choices=[(0, 'day'), (1, 'light on'), (2, 'light off')])),
                ('hit_and_run', models.BooleanField()),
                ('accident_place_name', models.CharField(max_length=100)),
                ('accident_location', models.CharField(max_length=100)),
                ('accident_location_latitude', models.DecimalField(decimal_places=5, max_digits=15)),
                ('accident_location_longitude', models.DecimalField(decimal_places=5, max_digits=15)),
                ('road_number', models.IntegerField()),
                ('road_length', models.IntegerField()),
                ('police_info', models.TextField()),
                ('investigation_officers_name', models.CharField(max_length=100)),
                ('investigation_officers_name_standard', models.IntegerField()),
                ('reinvestigation_officers_name', models.CharField(max_length=100)),
                ('reinvestigation_officers_name_standard', models.IntegerField()),
                ('noted_action', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('witness_name', models.CharField(max_length=500)),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accidents.Accident')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_registration_no', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_owner_name', models.CharField(max_length=100)),
                ('vehicle_owner_address', models.CharField(max_length=100)),
                ('third_party_insurance', models.BooleanField()),
                ('name_of_vehicle_company', models.CharField(max_length=100)),
                ('vehicle_type', models.IntegerField(choices=[(0, 'bicycle'), (1, 'Riksaw'), (2, 'Motorcycle'), (3, 'Autoriksaw'), (4, 'Car'), (5, 'Minibus'), (6, 'Bus'), (7, 'Truck'), (8, 'others')])),
                ('vehicle_action', models.IntegerField(choices=[(0, 'left turn'), (1, 'right turn'), (2, 'U turn'), (3, 'cross traffic'), (4, 'meeting action'), (5, 'departure action'), (6, 'overtack action'), (7, 'move ahead'), (8, 'move backward'), (9, 'instant start'), (10, 'instant stop'), (11, 'parking outside road'), (12, 'parking inside road'), (13, 'others')])),
                ('load_condition', models.IntegerField(choices=[(0, 'correct load according to law'), (1, 'extra load'), (2, 'insecure load'), (3, 'load come outside vehicle'), (4, 'others improper load')])),
                ('mistake', models.IntegerField(choices=[(0, 'No errors'), (1, 'Brakes'), (2, 'starring'), (3, 'Tyres'), (4, 'Vehicle lights'), (5, 'More than one errors in vehicle'), (6, 'Others')])),
                ('vehicle_loss', models.IntegerField(choices=[(0, 'No loss'), (1, 'Front'), (2, 'rear end'), (3, 'Right side '), (4, 'Left side'), (5, 'Roof'), (6, 'More than one losses'), (7, 'Others')])),
                ('owner_type', models.IntegerField(choices=[(0, 'Government worker'), (1, 'Institutional'), (2, 'Political'), (3, 'Private'), (4, 'Rent'), (5, 'Police'), (6, 'Army')])),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accidents.Accident')),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_runway_type', models.IntegerField(choices=[(0, 'one way'), (1, 'two way')])),
                ('intersection_type', models.IntegerField(choices=[(0, 'no  junction'), (1, '+ intersection'), (2, 'T intersection'), (3, 'Z intersection'), (4, 'Y intersection'), (5, 'circular intersection'), (6, 'others')])),
                ('road_description', models.IntegerField(choices=[(0, 'straight and plane'), (1, 'turns only'), (2, 'ups and downs'), (3, 'turns and ups and downs'), (4, 'Bridge')])),
                ('road_surface', models.IntegerField(choices=[(0, 'Pitched'), (1, 'Gravel'), (2, 'Soil')])),
                ('road_condition', models.IntegerField(choices=[(0, 'Good'), (1, 'Bad')])),
                ('surface_condition', models.IntegerField(choices=[(0, 'Dry'), (1, 'wet'), (2, 'mud'), (3, 'collected water')])),
                ('road_construction', models.BooleanField()),
                ('accident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accidents.Accident')),
            ],
        ),
        migrations.CreateModel(
            name='Pedestrian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedestrian_name', models.CharField(max_length=100)),
                ('pedestrian_address', models.CharField(max_length=100)),
                ('pedestrian_sex', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'other')])),
                ('pedestrian_age', models.IntegerField()),
                ('pedestrian_injury_seriousness', models.IntegerField(choices=[(0, 'death'), (1, 'serious injury'), (2, 'simple injury')])),
                ('pedestrian_condition', models.IntegerField(choices=[(0, 'At zebra crossing'), (1, '50 meter inside zebra crossing'), (2, 'at middle of the road'), (3, 'outside scene middle of road'), (4, 'At footpath')])),
                ('pedestrian_action', models.IntegerField(choices=[(0, 'No involvement'), (1, 'Road Crossing'), (2, 'Walking at middle of road'), (3, 'Walking at corner of road'), (4, 'Playing at road'), (5, 'Playing at footpath')])),
                ('pedestrian_alcohol_used', models.IntegerField(choices=[(0, 'No suspect'), (1, 'Suspectable')])),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accidents.Accident')),
            ],
        ),
        migrations.CreateModel(
            name='Passanger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passanger_name', models.CharField(max_length=100)),
                ('passanger_address', models.CharField(max_length=100)),
                ('vehicle_no', models.IntegerField()),
                ('passanger_sex', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'other')])),
                ('passanger_age', models.IntegerField()),
                ('injury_seriousness', models.IntegerField(choices=[(0, 'death'), (1, 'serious injury'), (2, 'simple injury')])),
                ('passanger_condition', models.IntegerField(choices=[(0, 'front seat'), (1, 'back seat'), (2, 'bicycle/motorcycle passanger'), (3, 'Bus Passanger'), (4, 'sitting outside'), (5, 'Hangging outside')])),
                ('passanger_action', models.IntegerField(choices=[(0, 'No involvement'), (1, 'Going in'), (2, 'Coming out'), (3, 'Fallen'), (4, 'others')])),
                ('passanger_seatbelt_or_helmet_used', models.BooleanField()),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accidents.Accident')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_address', models.CharField(max_length=100)),
                ('driver_licence_no', models.CharField(max_length=100)),
                ('report_taking_office', models.CharField(max_length=100)),
                ('driver_sex', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'other')])),
                ('driver_age', models.IntegerField()),
                ('driver_fault', models.IntegerField(choices=[(0, 'No fault'), (1, 'No concentration'), (2, 'Too fast'), (3, 'Too close'), (4, 'No signal'), (5, 'Wrong method for overtake'), (6, 'wrong directional turn'), (7, 'Tired or Sleepy'), (8, 'others')])),
                ('driving_licence_type', models.IntegerField(choices=[(0, 'Full Driving Licence'), (1, 'Trial Period'), (2, 'Temporary Driving Licence'), (3, 'No Premission')])),
                ('driver_injury_type', models.IntegerField(choices=[(0, 'Deathable'), (1, 'Serious injury'), (2, 'Normal injury'), (3, 'No injury')])),
                ('alcohol_used', models.IntegerField(choices=[(0, 'No suspect'), (1, 'Suspectable')])),
                ('seatbelt_or_helmet_used', models.BooleanField()),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accidents.Vehicle')),
            ],
        ),
    ]
